spring:
  datasource:
      url: jdbc:mysql://localhost:3306/springbatch?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
      username: local_rdb_master
      password: local_rdb
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      enabled: false # disable auto launching jobs
    jdbc:
      initialize-schema: always